### ISSUE TITLE
Does not work with 'nowrapscan' when s:move wants to wrap around

### ISSUE THREAD

**Issue by blueyed** [junegunn/vim-oblique#49]
When using `nowrapscan` there will be an error when searching for the last occurrence in the buffer:

> E385: search hit BOTTOM without match for: foo

The same happens for backward search (`?`), but then it's E384.

When used with a command like `d`, this error prevents the command from being executed.

The error appears to come from the command generated in `s:move`.

Here is a failing test, although a lot of the existing tests are failing for me
already:

    diff --git i/test/oblique.vader w/test/oblique.vader
    index 61ce0d3..378f3e5 100644
    --- i/test/oblique.vader
    +++ w/test/oblique.vader
    @@ -73,6 +73,18 @@ Expect:
     
       DEALINGS IN THE SOFTWARE.
     
    +Do (/ with command and nowrapscan):
    +  :set nowrapscan
    +  5G
    +  d/dealings\<cr>
    +
    +Expect:
    +  Copyright (c) 2014 Junegunn Choi
    +
    +  MIT License
    +
    +  DEALINGS IN THE SOFTWARE.
    +
     # CTRL-L
     # ==============================================================================

**Comment by junegunn** [comment]
Thanks for the report and the test case! Should be fixed now.

**Comment by blueyed** [comment]
Thanks for fixing this!
