### ISSUE TITLE
Can't properly clear search highlight

### ISSUE THREAD

**Issue by eugen0329** [junegunn/vim-oblique#55]
It seems this is not valid when the last match (means one matched sequence in the text, but not all other matches) staying highlighted even if I type :noh<CR>.

**Comment by junegunn** [comment]
Yeah, that one is manually highlighted (to have different color than the rest) so it's not affected by `:nohl` and it's not possible to override the behavior of`:nohl` without some hack as it's a builtin command. But the highlight is cleared as soon as the cursor is moved, so it doesn't really bother me.
