### ISSUE TITLE
Is it possible for n and N to search in constant direction

### ISSUE THREAD

**Issue by rgrinberg** [junegunn/vim-oblique#56]
I find it more comfortable to have `n` always search "down" the buffer and `N` always searches "up". I know you can tweak this with normal search from this link:

http://vi.stackexchange.com/questions/2365/how-can-i-get-n-to-go-forward-even-if-i-started-searching-with-or

Any way to accomplish this with oblique as well?

**Comment by junegunn** [comment]
Not currently. But I could add `<Plug>` mappings for the purpose.

**Comment by jyscao** [comment]
Hi Junegunn, it would be awesome if you could implement this as I'd love to see it too.

**Comment by junegunn** [comment]
This should work now:

```vim
nmap n <Plug>(Oblique-n!)
xmap n <Plug>(Oblique-n!)
nmap N <Plug>(Oblique-N!)
xmap N <Plug>(Oblique-N!)
```

**Comment by rgrinberg** [comment]
Awesome! Thanks @junegunn
