### ISSUE TITLE
Undocumented gd and gD mappings

### ISSUE THREAD

**Issue by sodapopcan** [junegunn/vim-oblique#57]
This threw me for a loop since `gd` has been my `Gdiff` mappings for a long time now.  I actually revisited what `gd` and `gD` actually do and realize they are actually pretty useful :)  In any event, they aren't mentioned anywhere and they also aren't over-ridable.  Maybe this is on purpose?  I thought I would point it out regardless.

**Comment by sodapopcan** [comment]
Oh, I didn't do due-diligence and only now saw #20.

**Comment by junegunn** [comment]
Yeah, those mappings are there to fix the linked issue. I just updated Oblique so that it does not override the existing mappings. Also, I added missing `gd` and `gD` for visual mode. Is there anything else you want me to address?

**Comment by sodapopcan** [comment]
Oh, thank you very much!  Nothing else, that's great thank you :)
