### ISSUE TITLE
Request: Center, etc. After Search

### ISSUE THREAD

**Issue by noctuid** [junegunn/vim-oblique#9]
With vim's normal search, you can do something like the following to open folds and center the line after a search:
`cnoremap <expr> <CR> getcmdtype() =~ "[/?]" ? "<CR>zzzv" : "<CR>"`
or 

```
let g:centeronsearch = "zzzv"
autocmd InsertEnter * let g:centeronsearch = "\<C-O>zz\<C-O>zv"
autocmd InsertLeave * let g:centeronsearch = "zzzv"
cnoremap <expr> <CR> "\<CR>" . ( getcmdtype() =~ "[/?]" ? g:centeronsearch : "" )
```

[source](http://www.reddit.com/r/vim/comments/2cjvxg/learning_vim_in_2014_search/cjh4e9p)

With vim-oblique, this just causes searching to freeze vim. An option to do something like this with Oblique-/ would be nice.

Edit: I see that folds are opened (issue #2) by default with oblique mappings, but using the above examples to center (with just `zz`) does freeze vim. I think adding centering as default or as an option to the plugin would be nice.

**Comment by blueyed** [comment]
@junegunn 
It would be nice if this could be done more conditionally, like described in https://www.reddit.com/r/vim/comments/4jy1mh/slightly_more_subltle_n_and_n_behavior/d3akyos / https://www.reddit.com/r/vim/comments/4jy1mh/slightly_more_subltle_n_and_n_behavior/d3bclmp, where it only gets done when the display was scrolled:

I came up with this:

```vim
" Improved n/N - center line after page scroll.
" Source: https://www.reddit.com/r/vim/comments/4jy1mh/slightly_more_subltle_n_and_n_behavior/d3bclmp.
if &rtp =~# '\<oblique\>'
  fun! s:oblique_nextzz(force)
    let topline  = line('w0')
    if a:force || get(s:, 'last_topline', 0) != topline
      normal! zz
    endif
    let s:last_topline = topline
  endfun
  autocmd User Oblique       call <SID>oblique_nextzz(1)
  autocmd User ObliqueStar   call <SID>oblique_nextzz(1)
  autocmd User ObliqueRepeat call <SID>oblique_nextzz(0)
else
  function! s:nextzz(cmd)
    let topline  = line('w0')
    let v:errmsg = ""
    execute "silent! normal! " . a:cmd
    if v:errmsg =~ 'E38[45]:.*'
      echohl Error | unsilent echom v:errmsg | echohl None
      let v:errmsg = ""
      return
    endif
    if topline != line('w0')
      normal! zz
    endif
  endfun
  nnoremap <silent> n :call <SID>nextzz('n')<cr>
  nnoremap <silent> N :call <SID>nextzz('N')<cr>
endif
```

**Comment by junegunn** [comment]
@blueyed Interesting, thanks.

**Comment by blueyed** [comment]
@junegunn 
You're welcome.
We might add that to the README, in case it works out for you, too.
